const CAMBIAR_USUARIO = "CAMBIAR_USUARIO";
const CAMBIAR_EMAIL = "CAMBIAR_EMAIL_USUARIO";
const CAMBIAR_NOMBRE = "CAMBIAR_NOMBRE_USUARIO";

export {
  CAMBIAR_USUARIO,
  CAMBIAR_EMAIL,
  CAMBIAR_NOMBRE
};
